# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gnoi/proto/_legacy/file/file.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gnoi.proto._legacy.types import types_pb2 as gnoi_dot_proto_dot___legacy_dot_types_dot_types__pb2
from gnoi.proto._legacy.common import common_pb2 as gnoi_dot_proto_dot___legacy_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gnoi/proto/_legacy/file/file.proto',
  package='gnoi.file',
  syntax='proto3',
  serialized_options=b'\322>\0050.1.0',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"gnoi/proto/_legacy/file/file.proto\x12\tgnoi.file\x1a$gnoi/proto/_legacy/types/types.proto\x1a&gnoi/proto/_legacy/common/common.proto\"\xb5\x01\n\nPutRequest\x12-\n\x04open\x18\x01 \x01(\x0b\x32\x1d.gnoi.file.PutRequest.DetailsH\x00\x12\x12\n\x08\x63ontents\x18\x02 \x01(\x0cH\x00\x12$\n\x04hash\x18\x03 \x01(\x0b\x32\x14.gnoi.types.HashTypeH\x00\x1a\x33\n\x07\x44\x65tails\x12\x13\n\x0bremote_file\x18\x01 \x01(\t\x12\x13\n\x0bpermissions\x18\x02 \x01(\rB\t\n\x07request\"\r\n\x0bPutResponse\"!\n\nGetRequest\x12\x13\n\x0bremote_file\x18\x01 \x01(\t\"S\n\x0bGetResponse\x12\x12\n\x08\x63ontents\x18\x01 \x01(\x0cH\x00\x12$\n\x04hash\x18\x02 \x01(\x0b\x32\x14.gnoi.types.HashTypeH\x00\x42\n\n\x08response\"c\n\x17TransferToRemoteRequest\x12\x12\n\nlocal_path\x18\x01 \x01(\t\x12\x34\n\x0fremote_download\x18\x02 \x01(\x0b\x32\x1b.gnoi.common.RemoteDownload\">\n\x18TransferToRemoteResponse\x12\"\n\x04hash\x18\x01 \x01(\x0b\x32\x14.gnoi.types.HashType\"\x1b\n\x0bStatRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"2\n\x0cStatResponse\x12\"\n\x05stats\x18\x01 \x03(\x0b\x32\x13.gnoi.file.StatInfo\"a\n\x08StatInfo\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x15\n\rlast_modified\x18\x02 \x01(\x04\x12\x13\n\x0bpermissions\x18\x03 \x01(\r\x12\x0c\n\x04size\x18\x04 \x01(\x04\x12\r\n\x05umask\x18\x05 \x01(\r\"$\n\rRemoveRequest\x12\x13\n\x0bremote_file\x18\x01 \x01(\t\"\x10\n\x0eRemoveResponse2\xd5\x02\n\x04\x46ile\x12\x38\n\x03Get\x12\x15.gnoi.file.GetRequest\x1a\x16.gnoi.file.GetResponse\"\x00\x30\x01\x12]\n\x10TransferToRemote\x12\".gnoi.file.TransferToRemoteRequest\x1a#.gnoi.file.TransferToRemoteResponse\"\x00\x12\x38\n\x03Put\x12\x15.gnoi.file.PutRequest\x1a\x16.gnoi.file.PutResponse\"\x00(\x01\x12\x39\n\x04Stat\x12\x16.gnoi.file.StatRequest\x1a\x17.gnoi.file.StatResponse\"\x00\x12?\n\x06Remove\x12\x18.gnoi.file.RemoveRequest\x1a\x19.gnoi.file.RemoveResponse\"\x00\x42\x08\xd2>\x05\x30.1.0b\x06proto3'
  ,
  dependencies=[gnoi_dot_proto_dot___legacy_dot_types_dot_types__pb2.DESCRIPTOR,gnoi_dot_proto_dot___legacy_dot_common_dot_common__pb2.DESCRIPTOR,])




_PUTREQUEST_DETAILS = _descriptor.Descriptor(
  name='Details',
  full_name='gnoi.file.PutRequest.Details',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='remote_file', full_name='gnoi.file.PutRequest.Details.remote_file', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='permissions', full_name='gnoi.file.PutRequest.Details.permissions', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=298,
)

_PUTREQUEST = _descriptor.Descriptor(
  name='PutRequest',
  full_name='gnoi.file.PutRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='open', full_name='gnoi.file.PutRequest.open', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contents', full_name='gnoi.file.PutRequest.contents', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hash', full_name='gnoi.file.PutRequest.hash', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PUTREQUEST_DETAILS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='request', full_name='gnoi.file.PutRequest.request',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=128,
  serialized_end=309,
)


_PUTRESPONSE = _descriptor.Descriptor(
  name='PutResponse',
  full_name='gnoi.file.PutResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=311,
  serialized_end=324,
)


_GETREQUEST = _descriptor.Descriptor(
  name='GetRequest',
  full_name='gnoi.file.GetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='remote_file', full_name='gnoi.file.GetRequest.remote_file', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=359,
)


_GETRESPONSE = _descriptor.Descriptor(
  name='GetResponse',
  full_name='gnoi.file.GetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='contents', full_name='gnoi.file.GetResponse.contents', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hash', full_name='gnoi.file.GetResponse.hash', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='response', full_name='gnoi.file.GetResponse.response',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=361,
  serialized_end=444,
)


_TRANSFERTOREMOTEREQUEST = _descriptor.Descriptor(
  name='TransferToRemoteRequest',
  full_name='gnoi.file.TransferToRemoteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='local_path', full_name='gnoi.file.TransferToRemoteRequest.local_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='remote_download', full_name='gnoi.file.TransferToRemoteRequest.remote_download', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=446,
  serialized_end=545,
)


_TRANSFERTOREMOTERESPONSE = _descriptor.Descriptor(
  name='TransferToRemoteResponse',
  full_name='gnoi.file.TransferToRemoteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash', full_name='gnoi.file.TransferToRemoteResponse.hash', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=547,
  serialized_end=609,
)


_STATREQUEST = _descriptor.Descriptor(
  name='StatRequest',
  full_name='gnoi.file.StatRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='gnoi.file.StatRequest.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=611,
  serialized_end=638,
)


_STATRESPONSE = _descriptor.Descriptor(
  name='StatResponse',
  full_name='gnoi.file.StatResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stats', full_name='gnoi.file.StatResponse.stats', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=640,
  serialized_end=690,
)


_STATINFO = _descriptor.Descriptor(
  name='StatInfo',
  full_name='gnoi.file.StatInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='gnoi.file.StatInfo.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_modified', full_name='gnoi.file.StatInfo.last_modified', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='permissions', full_name='gnoi.file.StatInfo.permissions', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='size', full_name='gnoi.file.StatInfo.size', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='umask', full_name='gnoi.file.StatInfo.umask', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=692,
  serialized_end=789,
)


_REMOVEREQUEST = _descriptor.Descriptor(
  name='RemoveRequest',
  full_name='gnoi.file.RemoveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='remote_file', full_name='gnoi.file.RemoveRequest.remote_file', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=791,
  serialized_end=827,
)


_REMOVERESPONSE = _descriptor.Descriptor(
  name='RemoveResponse',
  full_name='gnoi.file.RemoveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=829,
  serialized_end=845,
)

_PUTREQUEST_DETAILS.containing_type = _PUTREQUEST
_PUTREQUEST.fields_by_name['open'].message_type = _PUTREQUEST_DETAILS
_PUTREQUEST.fields_by_name['hash'].message_type = gnoi_dot_proto_dot___legacy_dot_types_dot_types__pb2._HASHTYPE
_PUTREQUEST.oneofs_by_name['request'].fields.append(
  _PUTREQUEST.fields_by_name['open'])
_PUTREQUEST.fields_by_name['open'].containing_oneof = _PUTREQUEST.oneofs_by_name['request']
_PUTREQUEST.oneofs_by_name['request'].fields.append(
  _PUTREQUEST.fields_by_name['contents'])
_PUTREQUEST.fields_by_name['contents'].containing_oneof = _PUTREQUEST.oneofs_by_name['request']
_PUTREQUEST.oneofs_by_name['request'].fields.append(
  _PUTREQUEST.fields_by_name['hash'])
_PUTREQUEST.fields_by_name['hash'].containing_oneof = _PUTREQUEST.oneofs_by_name['request']
_GETRESPONSE.fields_by_name['hash'].message_type = gnoi_dot_proto_dot___legacy_dot_types_dot_types__pb2._HASHTYPE
_GETRESPONSE.oneofs_by_name['response'].fields.append(
  _GETRESPONSE.fields_by_name['contents'])
_GETRESPONSE.fields_by_name['contents'].containing_oneof = _GETRESPONSE.oneofs_by_name['response']
_GETRESPONSE.oneofs_by_name['response'].fields.append(
  _GETRESPONSE.fields_by_name['hash'])
_GETRESPONSE.fields_by_name['hash'].containing_oneof = _GETRESPONSE.oneofs_by_name['response']
_TRANSFERTOREMOTEREQUEST.fields_by_name['remote_download'].message_type = gnoi_dot_proto_dot___legacy_dot_common_dot_common__pb2._REMOTEDOWNLOAD
_TRANSFERTOREMOTERESPONSE.fields_by_name['hash'].message_type = gnoi_dot_proto_dot___legacy_dot_types_dot_types__pb2._HASHTYPE
_STATRESPONSE.fields_by_name['stats'].message_type = _STATINFO
DESCRIPTOR.message_types_by_name['PutRequest'] = _PUTREQUEST
DESCRIPTOR.message_types_by_name['PutResponse'] = _PUTRESPONSE
DESCRIPTOR.message_types_by_name['GetRequest'] = _GETREQUEST
DESCRIPTOR.message_types_by_name['GetResponse'] = _GETRESPONSE
DESCRIPTOR.message_types_by_name['TransferToRemoteRequest'] = _TRANSFERTOREMOTEREQUEST
DESCRIPTOR.message_types_by_name['TransferToRemoteResponse'] = _TRANSFERTOREMOTERESPONSE
DESCRIPTOR.message_types_by_name['StatRequest'] = _STATREQUEST
DESCRIPTOR.message_types_by_name['StatResponse'] = _STATRESPONSE
DESCRIPTOR.message_types_by_name['StatInfo'] = _STATINFO
DESCRIPTOR.message_types_by_name['RemoveRequest'] = _REMOVEREQUEST
DESCRIPTOR.message_types_by_name['RemoveResponse'] = _REMOVERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PutRequest = _reflection.GeneratedProtocolMessageType('PutRequest', (_message.Message,), {

  'Details' : _reflection.GeneratedProtocolMessageType('Details', (_message.Message,), {
    'DESCRIPTOR' : _PUTREQUEST_DETAILS,
    '__module__' : 'gnoi.proto._legacy.file.file_pb2'
    # @@protoc_insertion_point(class_scope:gnoi.file.PutRequest.Details)
    })
  ,
  'DESCRIPTOR' : _PUTREQUEST,
  '__module__' : 'gnoi.proto._legacy.file.file_pb2'
  # @@protoc_insertion_point(class_scope:gnoi.file.PutRequest)
  })
_sym_db.RegisterMessage(PutRequest)
_sym_db.RegisterMessage(PutRequest.Details)

PutResponse = _reflection.GeneratedProtocolMessageType('PutResponse', (_message.Message,), {
  'DESCRIPTOR' : _PUTRESPONSE,
  '__module__' : 'gnoi.proto._legacy.file.file_pb2'
  # @@protoc_insertion_point(class_scope:gnoi.file.PutResponse)
  })
_sym_db.RegisterMessage(PutResponse)

GetRequest = _reflection.GeneratedProtocolMessageType('GetRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETREQUEST,
  '__module__' : 'gnoi.proto._legacy.file.file_pb2'
  # @@protoc_insertion_point(class_scope:gnoi.file.GetRequest)
  })
_sym_db.RegisterMessage(GetRequest)

GetResponse = _reflection.GeneratedProtocolMessageType('GetResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETRESPONSE,
  '__module__' : 'gnoi.proto._legacy.file.file_pb2'
  # @@protoc_insertion_point(class_scope:gnoi.file.GetResponse)
  })
_sym_db.RegisterMessage(GetResponse)

TransferToRemoteRequest = _reflection.GeneratedProtocolMessageType('TransferToRemoteRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRANSFERTOREMOTEREQUEST,
  '__module__' : 'gnoi.proto._legacy.file.file_pb2'
  # @@protoc_insertion_point(class_scope:gnoi.file.TransferToRemoteRequest)
  })
_sym_db.RegisterMessage(TransferToRemoteRequest)

TransferToRemoteResponse = _reflection.GeneratedProtocolMessageType('TransferToRemoteResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRANSFERTOREMOTERESPONSE,
  '__module__' : 'gnoi.proto._legacy.file.file_pb2'
  # @@protoc_insertion_point(class_scope:gnoi.file.TransferToRemoteResponse)
  })
_sym_db.RegisterMessage(TransferToRemoteResponse)

StatRequest = _reflection.GeneratedProtocolMessageType('StatRequest', (_message.Message,), {
  'DESCRIPTOR' : _STATREQUEST,
  '__module__' : 'gnoi.proto._legacy.file.file_pb2'
  # @@protoc_insertion_point(class_scope:gnoi.file.StatRequest)
  })
_sym_db.RegisterMessage(StatRequest)

StatResponse = _reflection.GeneratedProtocolMessageType('StatResponse', (_message.Message,), {
  'DESCRIPTOR' : _STATRESPONSE,
  '__module__' : 'gnoi.proto._legacy.file.file_pb2'
  # @@protoc_insertion_point(class_scope:gnoi.file.StatResponse)
  })
_sym_db.RegisterMessage(StatResponse)

StatInfo = _reflection.GeneratedProtocolMessageType('StatInfo', (_message.Message,), {
  'DESCRIPTOR' : _STATINFO,
  '__module__' : 'gnoi.proto._legacy.file.file_pb2'
  # @@protoc_insertion_point(class_scope:gnoi.file.StatInfo)
  })
_sym_db.RegisterMessage(StatInfo)

RemoveRequest = _reflection.GeneratedProtocolMessageType('RemoveRequest', (_message.Message,), {
  'DESCRIPTOR' : _REMOVEREQUEST,
  '__module__' : 'gnoi.proto._legacy.file.file_pb2'
  # @@protoc_insertion_point(class_scope:gnoi.file.RemoveRequest)
  })
_sym_db.RegisterMessage(RemoveRequest)

RemoveResponse = _reflection.GeneratedProtocolMessageType('RemoveResponse', (_message.Message,), {
  'DESCRIPTOR' : _REMOVERESPONSE,
  '__module__' : 'gnoi.proto._legacy.file.file_pb2'
  # @@protoc_insertion_point(class_scope:gnoi.file.RemoveResponse)
  })
_sym_db.RegisterMessage(RemoveResponse)


DESCRIPTOR._options = None

_FILE = _descriptor.ServiceDescriptor(
  name='File',
  full_name='gnoi.file.File',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=848,
  serialized_end=1189,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='gnoi.file.File.Get',
    index=0,
    containing_service=None,
    input_type=_GETREQUEST,
    output_type=_GETRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TransferToRemote',
    full_name='gnoi.file.File.TransferToRemote',
    index=1,
    containing_service=None,
    input_type=_TRANSFERTOREMOTEREQUEST,
    output_type=_TRANSFERTOREMOTERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Put',
    full_name='gnoi.file.File.Put',
    index=2,
    containing_service=None,
    input_type=_PUTREQUEST,
    output_type=_PUTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Stat',
    full_name='gnoi.file.File.Stat',
    index=3,
    containing_service=None,
    input_type=_STATREQUEST,
    output_type=_STATRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Remove',
    full_name='gnoi.file.File.Remove',
    index=4,
    containing_service=None,
    input_type=_REMOVEREQUEST,
    output_type=_REMOVERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FILE)

DESCRIPTOR.services_by_name['File'] = _FILE

# @@protoc_insertion_point(module_scope)
