# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gnoi/proto/_legacy/bgp/bgp.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gnoi.proto._legacy.types import types_pb2 as gnoi_dot_proto_dot___legacy_dot_types_dot_types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gnoi/proto/_legacy/bgp/bgp.proto',
  package='gnoi.bgp',
  syntax='proto3',
  serialized_options=b'\322>\0050.1.0',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n gnoi/proto/_legacy/bgp/bgp.proto\x12\x08gnoi.bgp\x1a$gnoi/proto/_legacy/types/types.proto\"\xa2\x01\n\x17\x43learBGPNeighborRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x18\n\x10routing_instance\x18\x02 \x01(\t\x12\x34\n\x04mode\x18\x03 \x01(\x0e\x32&.gnoi.bgp.ClearBGPNeighborRequest.Mode\"&\n\x04Mode\x12\x08\n\x04SOFT\x10\x00\x12\n\n\x06SOFTIN\x10\x01\x12\x08\n\x04HARD\x10\x02\"\x1a\n\x18\x43learBGPNeighborResponse2b\n\x03\x42GP\x12[\n\x10\x43learBGPNeighbor\x12!.gnoi.bgp.ClearBGPNeighborRequest\x1a\".gnoi.bgp.ClearBGPNeighborResponse\"\x00\x42\x08\xd2>\x05\x30.1.0b\x06proto3'
  ,
  dependencies=[gnoi_dot_proto_dot___legacy_dot_types_dot_types__pb2.DESCRIPTOR,])



_CLEARBGPNEIGHBORREQUEST_MODE = _descriptor.EnumDescriptor(
  name='Mode',
  full_name='gnoi.bgp.ClearBGPNeighborRequest.Mode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SOFT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SOFTIN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HARD', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=209,
  serialized_end=247,
)
_sym_db.RegisterEnumDescriptor(_CLEARBGPNEIGHBORREQUEST_MODE)


_CLEARBGPNEIGHBORREQUEST = _descriptor.Descriptor(
  name='ClearBGPNeighborRequest',
  full_name='gnoi.bgp.ClearBGPNeighborRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='gnoi.bgp.ClearBGPNeighborRequest.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='routing_instance', full_name='gnoi.bgp.ClearBGPNeighborRequest.routing_instance', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mode', full_name='gnoi.bgp.ClearBGPNeighborRequest.mode', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CLEARBGPNEIGHBORREQUEST_MODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=247,
)


_CLEARBGPNEIGHBORRESPONSE = _descriptor.Descriptor(
  name='ClearBGPNeighborResponse',
  full_name='gnoi.bgp.ClearBGPNeighborResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=275,
)

_CLEARBGPNEIGHBORREQUEST.fields_by_name['mode'].enum_type = _CLEARBGPNEIGHBORREQUEST_MODE
_CLEARBGPNEIGHBORREQUEST_MODE.containing_type = _CLEARBGPNEIGHBORREQUEST
DESCRIPTOR.message_types_by_name['ClearBGPNeighborRequest'] = _CLEARBGPNEIGHBORREQUEST
DESCRIPTOR.message_types_by_name['ClearBGPNeighborResponse'] = _CLEARBGPNEIGHBORRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClearBGPNeighborRequest = _reflection.GeneratedProtocolMessageType('ClearBGPNeighborRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLEARBGPNEIGHBORREQUEST,
  '__module__' : 'gnoi.proto._legacy.bgp.bgp_pb2'
  # @@protoc_insertion_point(class_scope:gnoi.bgp.ClearBGPNeighborRequest)
  })
_sym_db.RegisterMessage(ClearBGPNeighborRequest)

ClearBGPNeighborResponse = _reflection.GeneratedProtocolMessageType('ClearBGPNeighborResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLEARBGPNEIGHBORRESPONSE,
  '__module__' : 'gnoi.proto._legacy.bgp.bgp_pb2'
  # @@protoc_insertion_point(class_scope:gnoi.bgp.ClearBGPNeighborResponse)
  })
_sym_db.RegisterMessage(ClearBGPNeighborResponse)


DESCRIPTOR._options = None

_BGP = _descriptor.ServiceDescriptor(
  name='BGP',
  full_name='gnoi.bgp.BGP',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=277,
  serialized_end=375,
  methods=[
  _descriptor.MethodDescriptor(
    name='ClearBGPNeighbor',
    full_name='gnoi.bgp.BGP.ClearBGPNeighbor',
    index=0,
    containing_service=None,
    input_type=_CLEARBGPNEIGHBORREQUEST,
    output_type=_CLEARBGPNEIGHBORRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BGP)

DESCRIPTOR.services_by_name['BGP'] = _BGP

# @@protoc_insertion_point(module_scope)
