# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: github.com/openconfig/gnoi/types/types.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict, List

import betterproto


class L3Protocol(betterproto.Enum):
    """Generic Layer 3 Protocol enumeration."""

    UNSPECIFIED = 0
    IPV4 = 1
    IPV6 = 2


class HashTypeHashMethod(betterproto.Enum):
    UNSPECIFIED = 0
    SHA256 = 1
    SHA512 = 2
    MD5 = 3


@dataclass
class HashType(betterproto.Message):
    """
    HashType defines the valid hash methods for data verification.  UNSPECIFIED
    should be treated an error.
    """

    method: "HashTypeHashMethod" = betterproto.enum_field(1)
    hash: bytes = betterproto.bytes_field(2)


@dataclass
class Path(betterproto.Message):
    """
    Path encodes a data tree path as a series of repeated strings, with each
    element of the path representing a data tree node name and the associated
    attributes. Reference: gNMI Specification Section 2.2.2.
    """

    origin: str = betterproto.string_field(2)
    elem: List["PathElem"] = betterproto.message_field(3)


@dataclass
class PathElem(betterproto.Message):
    """
    PathElem encodes an element of a gNMI path, along with any attributes
    (keys) that may be associated with it. Reference: gNMI Specification
    Section 2.2.2.
    """

    name: str = betterproto.string_field(1)
    key: Dict[str, str] = betterproto.map_field(
        2, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass
class Credentials(betterproto.Message):
    """
    Credentials defines credentials needed to perform authentication on a
    device.
    """

    username: str = betterproto.string_field(1)
    cleartext: str = betterproto.string_field(2, group="password")
    hashed: "HashType" = betterproto.message_field(3, group="password")
