# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from gnoi.proto._legacy.layer2 import layer2_pb2 as gnoi_dot_proto_dot___legacy_dot_layer2_dot_layer2__pb2


class Layer2Stub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClearNeighborDiscovery = channel.unary_unary(
                '/gnoi.layer2.Layer2/ClearNeighborDiscovery',
                request_serializer=gnoi_dot_proto_dot___legacy_dot_layer2_dot_layer2__pb2.ClearNeighborDiscoveryRequest.SerializeToString,
                response_deserializer=gnoi_dot_proto_dot___legacy_dot_layer2_dot_layer2__pb2.ClearNeighborDiscoveryResponse.FromString,
                )
        self.ClearSpanningTree = channel.unary_unary(
                '/gnoi.layer2.Layer2/ClearSpanningTree',
                request_serializer=gnoi_dot_proto_dot___legacy_dot_layer2_dot_layer2__pb2.ClearSpanningTreeRequest.SerializeToString,
                response_deserializer=gnoi_dot_proto_dot___legacy_dot_layer2_dot_layer2__pb2.ClearSpanningTreeResponse.FromString,
                )
        self.PerformBERT = channel.unary_stream(
                '/gnoi.layer2.Layer2/PerformBERT',
                request_serializer=gnoi_dot_proto_dot___legacy_dot_layer2_dot_layer2__pb2.PerformBERTRequest.SerializeToString,
                response_deserializer=gnoi_dot_proto_dot___legacy_dot_layer2_dot_layer2__pb2.PerformBERTResponse.FromString,
                )
        self.ClearLLDPInterface = channel.unary_unary(
                '/gnoi.layer2.Layer2/ClearLLDPInterface',
                request_serializer=gnoi_dot_proto_dot___legacy_dot_layer2_dot_layer2__pb2.ClearLLDPInterfaceRequest.SerializeToString,
                response_deserializer=gnoi_dot_proto_dot___legacy_dot_layer2_dot_layer2__pb2.ClearLLDPInterfaceResponse.FromString,
                )
        self.SendWakeOnLAN = channel.unary_unary(
                '/gnoi.layer2.Layer2/SendWakeOnLAN',
                request_serializer=gnoi_dot_proto_dot___legacy_dot_layer2_dot_layer2__pb2.SendWakeOnLANRequest.SerializeToString,
                response_deserializer=gnoi_dot_proto_dot___legacy_dot_layer2_dot_layer2__pb2.SendWakeOnLANResponse.FromString,
                )


class Layer2Servicer(object):
    """Missing associated documentation comment in .proto file."""

    def ClearNeighborDiscovery(self, request, context):
        """ClearNeighborDiscovery will clear either a specific neighbor entry or
        clear the entire table based on parameters provided.
        TODO: This method is subject to deprecation once OpenConfig models this
        state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearSpanningTree(self, request, context):
        """ClearSpanningTree will reset a blocked spanning tree interface.
        TODO: This method is subject to deprecation once OpenConfig models this
        state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PerformBERT(self, request, context):
        """PerformBERT will perform a BERT operation on a port. The stream will
        return the current state of the operation as well as the ID for the
        operation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearLLDPInterface(self, request, context):
        """ClearLLDPInterface will clear all LLDP adjacencies on the provided
        interface.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendWakeOnLAN(self, request, context):
        """SendWakeOnLAN will send a WOL event on the requested interface.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Layer2Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClearNeighborDiscovery': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearNeighborDiscovery,
                    request_deserializer=gnoi_dot_proto_dot___legacy_dot_layer2_dot_layer2__pb2.ClearNeighborDiscoveryRequest.FromString,
                    response_serializer=gnoi_dot_proto_dot___legacy_dot_layer2_dot_layer2__pb2.ClearNeighborDiscoveryResponse.SerializeToString,
            ),
            'ClearSpanningTree': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearSpanningTree,
                    request_deserializer=gnoi_dot_proto_dot___legacy_dot_layer2_dot_layer2__pb2.ClearSpanningTreeRequest.FromString,
                    response_serializer=gnoi_dot_proto_dot___legacy_dot_layer2_dot_layer2__pb2.ClearSpanningTreeResponse.SerializeToString,
            ),
            'PerformBERT': grpc.unary_stream_rpc_method_handler(
                    servicer.PerformBERT,
                    request_deserializer=gnoi_dot_proto_dot___legacy_dot_layer2_dot_layer2__pb2.PerformBERTRequest.FromString,
                    response_serializer=gnoi_dot_proto_dot___legacy_dot_layer2_dot_layer2__pb2.PerformBERTResponse.SerializeToString,
            ),
            'ClearLLDPInterface': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearLLDPInterface,
                    request_deserializer=gnoi_dot_proto_dot___legacy_dot_layer2_dot_layer2__pb2.ClearLLDPInterfaceRequest.FromString,
                    response_serializer=gnoi_dot_proto_dot___legacy_dot_layer2_dot_layer2__pb2.ClearLLDPInterfaceResponse.SerializeToString,
            ),
            'SendWakeOnLAN': grpc.unary_unary_rpc_method_handler(
                    servicer.SendWakeOnLAN,
                    request_deserializer=gnoi_dot_proto_dot___legacy_dot_layer2_dot_layer2__pb2.SendWakeOnLANRequest.FromString,
                    response_serializer=gnoi_dot_proto_dot___legacy_dot_layer2_dot_layer2__pb2.SendWakeOnLANResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gnoi.layer2.Layer2', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Layer2(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClearNeighborDiscovery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gnoi.layer2.Layer2/ClearNeighborDiscovery',
            gnoi_dot_proto_dot___legacy_dot_layer2_dot_layer2__pb2.ClearNeighborDiscoveryRequest.SerializeToString,
            gnoi_dot_proto_dot___legacy_dot_layer2_dot_layer2__pb2.ClearNeighborDiscoveryResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClearSpanningTree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gnoi.layer2.Layer2/ClearSpanningTree',
            gnoi_dot_proto_dot___legacy_dot_layer2_dot_layer2__pb2.ClearSpanningTreeRequest.SerializeToString,
            gnoi_dot_proto_dot___legacy_dot_layer2_dot_layer2__pb2.ClearSpanningTreeResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PerformBERT(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/gnoi.layer2.Layer2/PerformBERT',
            gnoi_dot_proto_dot___legacy_dot_layer2_dot_layer2__pb2.PerformBERTRequest.SerializeToString,
            gnoi_dot_proto_dot___legacy_dot_layer2_dot_layer2__pb2.PerformBERTResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClearLLDPInterface(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gnoi.layer2.Layer2/ClearLLDPInterface',
            gnoi_dot_proto_dot___legacy_dot_layer2_dot_layer2__pb2.ClearLLDPInterfaceRequest.SerializeToString,
            gnoi_dot_proto_dot___legacy_dot_layer2_dot_layer2__pb2.ClearLLDPInterfaceResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendWakeOnLAN(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gnoi.layer2.Layer2/SendWakeOnLAN',
            gnoi_dot_proto_dot___legacy_dot_layer2_dot_layer2__pb2.SendWakeOnLANRequest.SerializeToString,
            gnoi_dot_proto_dot___legacy_dot_layer2_dot_layer2__pb2.SendWakeOnLANResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
